/*
 * WorkflowRunner.java
 *
 * Version 1.0  Sep 25, 2008
 *
 * Copyright notice
 *
 * Brief description
 *
 * (c) 2008 by dbreuer
 */
package de.fhkoeln.santiago.workflow;

import java.util.Iterator;
import java.util.Set;

import javax.xml.namespace.QName;

import org.apache.axis2.AxisFault;
import org.apache.axis2.addressing.EndpointReference;
import org.apache.axis2.client.Options;
import org.apache.axis2.rpc.client.RPCServiceClient;

import de.fhkoeln.santiago.services.IODescriptor;
import de.fhkoeln.santiago.services.OutputDescriptor;
import de.fhkoeln.santiago.workflow.WorkflowElement.Input;
import de.fhkoeln.santiago.workflow.storage.ProcessStore;

/**
 * A {@link WorkflowRunner} runs a workflow specified by its
 * {@link WorkflowDefinition} against the web service deployed
 * components.
 * 
 * @author dbreuer
 * @version 1.0 Sep 25, 2008
 */
public class WorkflowRunner {
  
  private WorkflowDefinition definition;
  private ProcessStore processStore;
  
  public void run() {
    /*
     * go through the definition and load the required data
     * so we can invoke the service component.
     * 
     * Thereby we have to take different aspects into account:
     *   - The service component either needs input or not
     *   - if so, two different kinds of input can occur
     *      - internal, which is generated by another component
     *      - external which may be a simple file
     *   - The components have a predecessor and a successor
     *   - Only a transformer component can have both
     *   - A transformer must have exactly the same number of
     *     inputs as it has predecessors
     *   
     */
    
    // iterate through the workflow definition elements
    while (definition.hasNextElements()) {
       for (WorkflowElement element : definition.getNextElements()) {
//      for (Iterator<WorkflowElement> iterator =
//          definition.getNextElements().iterator(); iterator.hasNext();) {
//        WorkflowElement element = iterator.next();
        // define a default inputDescriptor
        IODescriptor inputDescriptor = new IODescriptor();

        if (element.needsInput()) {

          for (Input elementInput : element.getInput()) {
            if (elementInput.isExternal()) {
              inputDescriptor.add(elementInput.getData());
            } else if (elementInput.isInternal()) {
              inputDescriptor.add(getStorage().getInputByKey(
                  elementInput.getUri()));
            }
          }

        } 

        IODescriptor outputDescriptor = invokeServiceForElementWithInputDescriptor(element, inputDescriptor);
        
        if (!outputDescriptor.isEmpty()) {
          getStorage().putDataForKey(outputDescriptor.first(), element.getOutputUri());
        }
      }
    }
  }
  
  /**
   * @return The store which holds temporary information of the process
   */
  public ProcessStore getStorage() {
    return processStore;
  }
  
  public void setProcessStore(ProcessStore processStore) {
    this.processStore = processStore;
  }

  public void setDefinition(WorkflowDefinition definition) {
    this.definition = definition;
  }
  
  public WorkflowDefinition getDefinition() {
    return definition;
  }

  /**
   * This method encapsulated the call of the remote service.
   * 
   * TODO: Namespace should be externalized
   * 
   * @param element
   *          The WorkflowElement of which we call its service
   * @param inputDescriptor
   *          The InputDescriptor for the service
   * @return An OutputDescriptor which holds the result of the service
   *         invocation.
   */
  private IODescriptor invokeServiceForElementWithInputDescriptor(
      WorkflowElement element, IODescriptor inputDescriptor) {

    IODescriptor output = new OutputDescriptor();
    
    try {
      RPCServiceClient client = new RPCServiceClient();
      
      Options options = client.getOptions();
      
      System.out.println("Setting EPR to: " + element.getUri());
      EndpointReference targetEPR = new EndpointReference(element.getUri());
      
      options.setTo(targetEPR);

      // Setting Input Params first
      QName setInputOperation = new QName("http://services.demo.santiago.fhkoeln.de", "setInput");
      
      Object[] setInputOperationArgs = new Object[] { inputDescriptor };
      
      client.invokeRobust(setInputOperation, setInputOperationArgs);
      
      // Run the service action and get back the output params
      QName executeOperation = new QName("http://services.demo.santiago.fhkoeln.de", "execute");
      
      Object[] executeOperationArgs = new Object[] {};
      Class[] returnTypes = new Class[] { IODescriptor.class };
      
      Object[] response = client.invokeBlocking(executeOperation, executeOperationArgs, returnTypes);
      
      output = (IODescriptor) response[0];
    } catch (AxisFault e) {
      e.printStackTrace();
    }
    
    // TODO Auto-generated method stub
    return output;
  }

}
